version: "3.5"

networks:
  core.network:
    name: "core.network"
    driver: bridge

volumes:
  db.postgres:
    driver: local

services:
  db:
    image: postgres
    volumes:
      - db.postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=core
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    networks:
      - core.network

  rest_api:
      build:
        context: .
        dockerfile: Dockerfile
      networks:
        - core.network
      volumes:
        - .:/usr/src/app
      ports:
        - "8000:8000"
      env_file:
        - .env
      depends_on:
        - db

  
