# Generated by Django 4.2.1 on 2023-06-15 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=800)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'db_table': 'fields',
            },
        ),
        migrations.CreateModel(
            name='ProposalFieldAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.fieldsmodel')),
            ],
            options={
                'verbose_name': 'Atribuição de questão',
                'verbose_name_plural': 'Atribuições de questões',
                'db_table': 'proposal_field_assignment',
            },
        ),
        migrations.CreateModel(
            name='ProposalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=800)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('proposal_situation', models.CharField(choices=[('Em análise', 'Em análise'), ('Aprovada', 'Aprovada'), ('Negada', 'Negada')], default='Em análise', max_length=50)),
                ('field', models.ManyToManyField(related_name='pillars', through='proposal.ProposalFieldAssignment', to='proposal.fieldsmodel')),
            ],
            options={
                'verbose_name': 'Proposta',
                'verbose_name_plural': 'Propostas',
                'db_table': 'proposal',
            },
        ),
        migrations.AddField(
            model_name='proposalfieldassignment',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_assignments', to='proposal.proposalmodel'),
        ),
    ]
